# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import demo_pb2 as demo__pb2


class GRPCDemoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SimpleGetMethod = channel.unary_unary(
        '/demo.GRPCDemo/SimpleGetMethod',
        request_serializer=demo__pb2.StrRequest.SerializeToString,
        response_deserializer=demo__pb2.Response.FromString,
        )
    self.SimplePostMethod = channel.unary_unary(
        '/demo.GRPCDemo/SimplePostMethod',
        request_serializer=demo__pb2.Request.SerializeToString,
        response_deserializer=demo__pb2.StrResponse.FromString,
        )


class GRPCDemoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SimpleGetMethod(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimplePostMethod(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GRPCDemoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SimpleGetMethod': grpc.unary_unary_rpc_method_handler(
          servicer.SimpleGetMethod,
          request_deserializer=demo__pb2.StrRequest.FromString,
          response_serializer=demo__pb2.Response.SerializeToString,
      ),
      'SimplePostMethod': grpc.unary_unary_rpc_method_handler(
          servicer.SimplePostMethod,
          request_deserializer=demo__pb2.Request.FromString,
          response_serializer=demo__pb2.StrResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demo.GRPCDemo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
